In [1]:
# Código Python 
resultado  =  0 
for  i  in range( 100 ): 
    resultado  +=  i
print(resultado)
# O resultado é 4950 porque o laço for soma todos os números de 0 até 99.
# Isso equivale à soma dos 100 primeiros números inteiros: 0 + 1 + 2 + ... + 99.
# A soma pode ser calculada pela fórmula n*(n-1)/2, onde n=100: 100*99/2 = 4950.

4950


LISTA EM PYTHON

In [2]:
lista = list(range(10))
print(lista)
type(lista)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


list

In [4]:
lista = [str(i) for i in range(10)]
print(lista)
type(lista[0])


['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


str

In [5]:
lista = [True, '2', 3.0, 4]
[type(item) for item in lista]
# Este código cria uma lista chamada 'lista' contendo quatro elementos de tipos diferentes: 
# um booleano (True), uma string ('2'), um float (3.0) e um inteiro (4).
# Em seguida, a expressão [type(item) for item in lista] cria uma nova lista que contém o tipo de cada elemento da lista original.
# O resultado será: [bool, str, float, int], mostrando os tipos de dados de cada item na lista.


[bool, str, float, int]

A vantagem da lista é a flexibilidade: como cada elemento da lista é uma estrutura completa contendo dados e informações de tipo, a lista pode ser preenchida com dados de qualquer tipo desejado. Arrays de tipo fixo no estilo NumPy não possuem essa flexibilidade, mas são muito mais eficientes para armazenar e manipular dados.

MATRIZES DE TIPO FIXO EM PYTHON

O Python oferece diversas opções para armazenar dados em buffers de dados eficientes e de tipo fixo. O módulo integrado array(disponível desde o Python 3.3) pode ser usado para criar matrizes densas de um tipo uniforme:

In [6]:
import array
lista = list(range(10))
A = array.array('i', lista)
print(A)
# Este código cria uma lista chamada 'lista' contendo os números de 0 a 9.
# Em seguida, ele cria um array de tipo inteiro (representado pelo código 'i') a partir da lista.
# O array resultante é armazenado na variável 'A'.
# O print(A) exibe o conteúdo do array 'A', que é [0, 1, 2, 3, 4, 5, 6, 7, 8, 9].
# O código 'array.array('i', lista)' cria um array de tipo inteiro a partir da lista 'lista'.


array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


Criando Matrizes a partir de listas em Python

In [2]:
import numpy as np

# Matriz de inteiros
np.array([1, 4, 2, 5, 3])
# Este código cria um array NumPy a partir de uma lista de números inteiros.
# O método np.array() é usado para converter a lista em um array NumPy.


array([1, 4, 2, 5, 3])

In [3]:
# Matriz de floats
'''Lembre-se de que, ao contrário das listas do Python, o NumPy é limitado a matrizes que contêm todos o mesmo tipo. Se os tipos não corresponderem, o NumPy fará uma conversão ascendente, se possível'''

np.matrix([3.14, 4, 2, 3])
# Este código cria um array NumPy a partir de uma lista de números de ponto flutuante.
# O método np.matrix() é usado para converter a lista em uma matriz NumPy.


matrix([[3.14, 4.  , 2.  , 3.  ]])

In [4]:
'''Se quisermos definir explicitamente o tipo de dados do array resultante, podemos usar a dtypepalavra-chave:'''

np.array([1, 2, 3], dtype=float)
# Este código cria um array NumPy a partir de uma lista de números inteiros.
# O método np.array() é usado para converter a lista em um array NumPy.
# A palavra-chave dtype=float define que o tipo de dados do array resultante será float.





array([1., 2., 3.])

In [ ]:
'''Por fim, diferentemente das listas do Python, os arrays NumPy podem ser explicitamente multidimensionais; aqui está uma maneira de inicializar um array multidimensional usando uma lista de listas:'''

# listas aninhadas resultam em matrizes multidimensionais 
np.array([range(i, i + 3) for i in [2, 4, 6]])

# Este código cria um array NumPy bidimensional (ou seja, uma matriz) a partir de uma lista de listas.
# Cada sublista representa uma linha da matriz. O método np.array() converte essas listas aninhadas em um array multidimensional.
# Assim, o resultado é uma matriz 2x3, onde:
# [[1, 2, 3],
#  [4, 5, 6]]


CRIANDO MATRIZES DO ZERO

Especialmente para matrizes maiores, é mais eficiente criá-las do zero usando rotinas integradas ao NumPy. Aqui estão alguns exemplos:

In [7]:
# Crie um array inteiro de comprimento 10 preenchido com zeros 
np.zeros ( 10 ,  dtype = int )

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
# Crie uma matriz de ponto flutuante 3x5 preenchida com uns 
np.ones (( 3 ,  5 ),  dtype = float )


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
# Crie um array 3x5 preenchido com 3,14 
np.full (( 3 ,  5 ),  3.14 )

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [12]:
# Crie uma matriz preenchida com uma sequência linear 
# Começando em 0, terminando em 20, incrementando em 2 
# (isso é semelhante à função range() interna) 
np.arange ( 0 ,  20 ,  2 )

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
# Crie uma matriz de cinco valores uniformemente espaçados entre 0 e 1 
np.linspace ( 0 ,  1 ,  5 )

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
# Crie uma matriz 3x3 de valores aleatórios distribuídos uniformemente entre 0 e 1 
np.random.random (( 3 ,  3 ))

array([[0.04827223, 0.48155986, 0.02882782],
       [0.43890717, 0.0786423 , 0.8228343 ],
       [0.01654509, 0.66578026, 0.55326025]])

In [17]:
# Crie uma matriz 3x3 de valores aleatórios distribuídos normalmente 
# com média 0 e desvio padrão 1 
np.random.normal ( 0 ,  1 ,  ( 3 ,  3 ))

array([[ 1.59302596, -0.90794608, -0.76131718],
       [ 0.48840364,  0.42996349,  1.27225707],
       [-1.2816517 , -0.29127101,  0.15852956]])

In [18]:
# Crie uma matriz 3x3 de inteiros aleatórios no intervalo [0, 10) 
np.random.randint ( 0 ,  10 ,  ( 3 ,  3 ))

array([[1, 6, 1],
       [5, 2, 7],
       [9, 2, 0]], dtype=int32)

In [19]:
# Crie uma matriz não inicializada de três inteiros 
# Os valores serão o que já existir naquele local de memória 
np.empty( 3 )

array([1., 2., 3.])

In [20]:
import numpy as np
import time

# cria uma lista com 1000000 elementos
lista = list(range(1000000))

# transforma a lista em um array Numpy
array = np.array(lista)

# começa a cronometrar o tempo para a operação com a lista
start_time = time.time()

# realiza a operação de elevar ao quadrado cada elemento da lista
lista_quadrado = [i**2 for i in lista]

# para o cronômetro
list_time = time.time() - start_time

# começa a cronometrar o tempo para a operação com o array
start_time = time.time()

# realiza a operação de elevar ao quadrado cada elemento do array
array_quadrado = array**2

# para o cronômetro
array_time = time.time() - start_time

print("Tempo da operação com a lista: ", list_time)
print("Tempo da operação com o array: ", array_time)

Tempo da operação com a lista:  0.15294575691223145
Tempo da operação com o array:  0.00566554069519043


Claro! Aqui estão os métodos do NumPy usados no documento Compreendendo os tipos de dados em Python.ipynb:

numpy.array: Cria um array NumPy a partir de listas ou outras sequências. Permite especificar o tipo de dados com o argumento dtype e pode criar arrays multidimensionais a partir de listas aninhadas.

numpy.matrix: Cria uma matriz NumPy bidimensional. É semelhante ao array, mas sempre retorna uma matriz 2D. (Obs: O uso de matrix é desencorajado em novos códigos, prefira array.)

numpy.zeros: Cria um array preenchido com zeros. Você pode definir o tamanho e o tipo de dados do array.

numpy.ones: Cria um array preenchido com uns. Também permite definir o formato e o tipo de dados.

numpy.full: Cria um array preenchido com um valor constante especificado.

numpy.arange: Gera um array com valores em uma sequência, semelhante à função range do Python, mas retorna um array NumPy.

numpy.linspace: Gera um array com valores igualmente espaçados em um intervalo definido.

numpy.random.random: Gera um array com valores aleatórios distribuídos uniformemente entre 0 e 1.

numpy.random.normal: Gera um array com valores aleatórios seguindo uma distribuição normal (gaussiana), com média e desvio padrão definidos.

numpy.random.randint: Gera um array de inteiros aleatórios em um intervalo especificado.

numpy.empty: Cria um array sem inicializar os valores (os valores serão o que já existir na memória naquele local).

Todos esses métodos são usados para criar e manipular arrays NumPy de diferentes formas e com diferentes tipos de dados. Se quiser exemplos de uso para algum deles, é só pedir!